CREATE EXTENSION IF NOT EXISTS PGCRYPTO;

CREATE TABLE ORGANIZATIONS (
    ID SERIAL PRIMARY KEY,
    -- user memomic ID
    VID TEXT NOT NULL UNIQUE CHECK (VID = LOWER(VID)),
    NAME TEXT NOT NULL,
    ENABLED BOOLEAN NOT NULL DEFAULT FALSE,
    TOKEN TEXT NOT NULL DEFAULT ENCODE(GEN_RANDOM_BYTES(32), 'hex')
);

CREATE TABLE DOMAINS (
    DOMAIN TEXT NOT NULL PRIMARY KEY,
    ORGANIZATION SERIAL REFERENCES ORGANIZATIONS(ID)
);

CREATE TABLE MEMBERSHIPS (
    -- user ID: (user is a keyword)
    ID TEXT NOT NULL PRIMARY KEY,
    ORGANIZATION SERIAL REFERENCES ORGANIZATIONS(ID),
    OWNER BOOLEAN NOT NULL,
    UNIQUE(ID, ORGANIZATION)
);
