CREATE EXTENSION IF NOT EXISTS PGCRYPTO;

CREATE TABLE ORGANIZATIONS (
    ID SERIAL PRIMARY KEY,
    NAME TEXT NOT NULL,
    ENABLED BOOLEAN NOT NULL,
    TOKEN TEXT NOT NULL DEFAULT ENCODE(GEN_RANDOM_BYTES(32), 'hex')
);

CREATE TABLE DOMAINS (
    DOMAIN TEXT NOT NULL PRIMARY KEY UNIQUE,
    ORGANIZATION SERIAL REFERENCES ORGANIZATIONS(ID)
);
